name: Lint

on:
  pull_request:
    branches: [develop, main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: ESLint Check
        run: yarn lint
